### ISSUE TITLE
Sharing of you Gerber Web viewer 

### ISSUE THREAD

**Issue by aeonSolutions** [hpcreery/GRX#5]
Hi @phcreery , @hpcreery 
great work!
just to let you know I'm sharing 😍 and adding a link to your project on my Github. 
You can find it here:
[https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/DIY-Maker/README.md](https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/DIY-Maker/README.md)

👍

**Comment by hpcreery** [comment]
Hello @aeonSolutions ,
Thank you so much for the feedback, all recognition is greatly appreciated!
I am also glad to find your use of this project.
